server:
  port: 8081

spring:
  application:
    name: customer-service
  cloud:
    inetutils:
      default-hostname: localhost
      ignored-interfaces:
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:
        - 192.168
        - 10.0
        - 172.16

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_service_db
    username: njiri
    password: njiri123#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-missing-locations: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: localhost:${server.port}
    status-page-url-path: ${server.servlet.context-path:}/actuator/info
    health-check-url-path: ${server.servlet.context-path:}/actuator/health
    lease-renewal-interval-in-seconds: 30
    home-page-url: http://localhost:${server.port}/

